name: Desplegar a GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar dependencias
        run: npm install
      
      - name: Construir sitio
        run: npm run build

      - name: Instalar rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
